# Generated by Django 4.2.4 on 2023-08-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0003_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
