# Generated by Django 4.2.4 on 2023-08-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0008_alter_advertisement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='Отметьте, если торг уместен', null=True, verbose_name='Торг'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='author',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='category',
            field=models.SmallIntegerField(null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='creatied_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='advertisement',
            table=None,
        ),
    ]
