# Generated by Django 4.2.4 on 2023-08-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0010_remove_advertisement_author_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
