# Generated by Django 4.2.4 on 2023-08-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0012_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='photo',
            field=models.ImageField(default=1, upload_to='FNAF', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
