# Generated by Django 4.2.4 on 2023-08-20 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0014_rename_description_advertisement_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='creatied_at',
            new_name='created_date',
        ),
    ]
