# Generated by Django 4.2.4 on 2023-08-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FNAF', '0015_rename_creatied_at_advertisement_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
